/**
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WorkflowIdeModule extends AbstractWorkflowIdeModule {
}
