apiVersion: v1
kind: Service
metadata:
  name: api-gateway-server
  labels:
    app: api-gateway-server
spec:
  type: NodePort
  selector:
    app: api-gateway-server
  ports:
    - name: http
      port: {{ .Values.service.api_gateway.port }}
      targetPort: {{ .Values.service.api_gateway.targetPort }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway-server
spec:
  replicas: {{ .Values.deployment.api_gateway.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway-server
  template:
    metadata:
      labels:
        app: api-gateway-server
    spec:
      containers:
        - name: api-gateway-server
          image: {{ .Values.deployment.api_gateway.image }}:{{ .Values.deployment.api_gateway.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.deployment.api_gateway.containerPort }}
          env:
            - name: JAVA_OPTS
              value: ' -DEUREKA_SERVER=http://registry-app-server:8761/eureka -DSTORAGE_SERVICE=http://storage-app-server:8089/ '

