apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  type: ClusterIP 
  selector:
    app: auth-server
  ports:
    - name: http
      port: {{ .Values.service.authorization_server.port }}
      targetPort: {{ .Values.service.authorization_server.targetPort }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
  labels:
    app: auth-server
spec:
  replicas: {{ .Values.deployment.authorization_server.replicaCount }}
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: {{ .Values.deployment.authorization_server.image }}:{{ .Values.deployment.authorization_server.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.deployment.authorization_server.containerPort }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mysql-secret
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-mysql-conf
                  key: db_url          
            - name: JAVA_OPTS
              value: ' -DEUREKA_SERVER=http://registry-app-server:8761/eureka 
                       -DZIPKIN_SERVER=http://zipkin:9411/'

