apiVersion: v1
kind: Service
metadata:
  name: dsl-backend-server
  labels:
    app: dsl-backend-server
spec:
  type: NodePort
  selector:
    app: dsl-backend-server
  ports:
    - name: http
      nodePort: 30100
      port: {{ .Values.service.dsl_backend.port }}
      targetPort: {{ .Values.service.dsl_backend.targetPort }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsl-backend-deployment
  labels:
    app: dsl-backend-server
spec:
  replicas: {{ .Values.deployment.dsl_backend.replicaCount }}
  selector:
    matchLabels:
      app: dsl-backend-server
  template:
    metadata:
      labels:
        app: dsl-backend-server
    spec:
      containers:
        - name: dsl-backend-server
          image: {{ .Values.deployment.dsl_backend.image }}:{{ .Values.deployment.dsl_backend.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.deployment.dsl_backend.containerPort }}


