apiVersion: v1
kind: Service
metadata:
  name: dsl-frontend-server
  labels:
    app: dsl-frontend-server
spec:
  type: NodePort 
  selector:
    app: dsl-frontend-server
  ports:
    - name: http
      nodePort: 30200
      port: {{ .Values.service.dsl_frontend.port }}
      targetPort: {{ .Values.service.dsl_frontend.targetPort }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsl-frontend-deployment
  labels:
    app: dsl-frontend-server
spec:
  replicas: {{ .Values.deployment.dsl_frontend.replicaCount }}
  selector:
    matchLabels:
      app: dsl-frontend-server
  template:
    metadata:
      labels:
        app: dsl-frontend-server
    spec:
      containers:
        - name: dsl-frontend-server
          image: {{ .Values.deployment.dsl_frontend.image }}:{{ .Values.deployment.dsl_frontend.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.deployment.dsl_frontend.containerPort }}


