apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/add-base-url: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"



  name: example
  # namespace: foo
spec:
  rules:
    - host: 34.107.29.78.sslip.io
      http:
        paths:
          - backend:
              serviceName: registry-app-server
              servicePort: 8761
            path: / #eureka/(.*)
          - backend:
              serviceName: api-gateway-server
              servicePort: 7000
            path: /api(/|$)(.*)

          - backend:
              serviceName: storage-app-server
              servicePort: 8089
            path: /store(/|$)(.*)
