apiVersion: v1
kind: Service
metadata:
  name: storage-app-server
  labels:
    app: storage-app-server
spec:
  type: NodePort
  selector:
    app: storage-app-server
  ports:
    - name: http
      port: {{ .Values.service.storage_api.port }} 
      targetPort: {{ .Values.service.storage_api.targetPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-app-deployment
  labels:
    app: storage-app-server
spec:
  replicas: {{ .Values.deployment.storage_api.replicaCount }}
  selector:
    matchLabels:
      app: storage-app-server
  template:
    metadata:
      labels:
        app: storage-app-server
    spec:
      containers:
        - name: storage-app-server
          image: {{ .Values.deployment.storage_api.image }}:{{ .Values.deployment.storage_api.tag }} 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.deployment.storage_api.containerPort }}
          # resources:
          #   limits:
          #     cpu: 0.5
          #     memory: "200Mi"
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-conf
                  key: db_url
        
            - name: JAVA_OPTS
              value: ' -DEUREKA_SERVER=http://registry-app-server:8761/eureka 
                       -DZIPKIN_SERVER=http://zipkin:9411/'
