apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: zipkin
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.service.zipkin.port }}
    targetPort: {{ .Values.service.zipkin.port }}
  selector:
    app: zipkin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zipkin
  name: zipkin
spec:
  replicas: {{ .Values.deployment.zipkin.replicaCount }}
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - env:
        - name: STORAGE_TYPE
          value: mem
        image: {{ .Values.deployment.zipkin.image }}:{{ .Values.deployment.zipkin.tag }}
        imagePullPolicy: IfNotPresent
        name: zipkin
        ports:
        - containerPort: {{ .Values.deployment.zipkin.containerPort }}
        