spring:
  application:
    name: eureka-registry-server
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

server:
  port: ${port:8761}
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    prefer-ip-address: true

