/*
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link WorkflowWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractWorkflowWebModule extends DefaultWebModule {

}
