/**
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.ui.quickfix;

import com.arsene.workflow.validation.WorkflowValidator;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.Fixes;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class WorkflowQuickfixProvider extends DefaultQuickfixProvider {
  @Fixes({ @Fix(WorkflowValidator.WORKFLOW_INVALID_NAME), @Fix(WorkflowValidator.METHOD_INVALID_NAME), @Fix(WorkflowValidator.VARIABLE_INVALID_NAME) })
  public void lowerCaseFisrtLetter(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      final IXtextDocument xtextDocument = context.getXtextDocument();
      final String firstLetter = xtextDocument.get((issue.getOffset()).intValue(), 1);
      xtextDocument.replace((issue.getOffset()).intValue(), 1, firstLetter.toLowerCase());
    };
    acceptor.accept(issue, "Make the first letter lower case", "Make the first letter small letter", "Workflow.png", _function);
  }
}
