apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap 
data:
  db_url: jdbc:mysql://storage-service:3306/model_storage?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
