/*
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.parser.antlr;

import com.arsene.workflow.parser.antlr.internal.InternalWorkflowParser;
import com.arsene.workflow.services.WorkflowGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WorkflowParser extends AbstractAntlrParser {

	@Inject
	private WorkflowGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWorkflowParser createParser(XtextTokenStream stream) {
		return new InternalWorkflowParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "WorkflowProgramModel";
	}

	public WorkflowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WorkflowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
