/*
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WorkflowAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/arsene/workflow/parser/antlr/internal/InternalWorkflow.tokens");
	}
}
