version: "3"
volumes:
  prometheus_data: {}
  
services:

#  eureka-naming-service:
#    image: eureka-naming-server
#    build:
#      context: ../eureka-naming-server
#    ports:
#      - "8761:8761"
#    # The virtual network where we will set up our private network
#    networks:
#      - test-network
#
#
#  product-stock-service:
#    image: product-stock-service
#    build:
#      context: ../product-stock-service
#    environment:
#      - JAVA_OPTS=
#        -DEUREKA_SERVER=http://eureka-naming-service:8761/eureka
##        -DZIPKIN_SERVER=http://zipkin:9411/
#    ports:
#      - "8800:8800"
#    #    links:
#    #      - zipkin
#    depends_on:
#      - eureka-naming-service
#    #      - zipkin
#    networks:
#      - test-network


  product-enquiry-service:
    image: product-enquiry-service
    build:
      context: ../product-enquiry-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-naming-service:8761/eureka
#        -DZIPKIN_SERVER=http://zipkin:9411/
    ports:
      - "8700:8700"
    #   links:
    #     - zipkin
#    depends_on:
#      - product-stock-service
    #     - zipkin
    networks:
      - test-network

#
#  spring-cloud-api-gateway-service:
#    image: spring-cloud-api-gateway-service
#    build:
#      context: ../spring-cloud-api-gateway-service
#    environment:
#      - JAVA_OPTS=
#        -DEUREKA_SERVER=http://eureka-naming-service:8761/eureka
##        -DZIPKIN_SERVER=http://zipkin:9411/
# #       -DENQUIRY_SERVICE=http://product-enquiry-service:9700/
#    ports:
#      - "8900:8900"
#    #   links:
#    #     - zipkin
#    depends_on:
#      - eureka-naming-service
#      - product-enquiry-service
#      - product-stock-service
#    #      - zipkin
#    networks:
#      - test-network


#  prometheus:
#    image: prom/prometheus
#    volumes:
#      - ./config/:/etc/prometheus
#      - ./data/prometheus:/data
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--storage.tsdb.retention=31d'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
#    ports:
#      - "9090:9090"
#    depends_on:
#      - product-stock-service
#    networks:
#      - test-network
#
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    depends_on:
#      - prometheus
#    networks:
#      - test-network
#
#
#  zipkin:
#    image: openzipkin/zipkin
#    environment:
#      - STORAGE_TYPE=mem
#    ports:
#      - "9411:9411"
#    depends_on:
#      - eureka-naming-service
#    networks:
#      - test-network



networks:
  test-network:

