/**
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.workflow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arsene.workflow.workflow.Assignment#getVariable <em>Variable</em>}</li>
 *   <li>{@link com.arsene.workflow.workflow.Assignment#getExpression <em>Expression</em>}</li>
 *   <li>{@link com.arsene.workflow.workflow.Assignment#getMethodInvocation <em>Method Invocation</em>}</li>
 * </ul>
 *
 * @see com.arsene.workflow.workflow.WorkflowPackage#getAssignment()
 * @model
 * @generated
 */
public interface Assignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(Variable)
   * @see com.arsene.workflow.workflow.WorkflowPackage#getAssignment_Variable()
   * @model
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link com.arsene.workflow.workflow.Assignment#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see com.arsene.workflow.workflow.WorkflowPackage#getAssignment_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link com.arsene.workflow.workflow.Assignment#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Method Invocation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Invocation</em>' containment reference.
   * @see #setMethodInvocation(Expression)
   * @see com.arsene.workflow.workflow.WorkflowPackage#getAssignment_MethodInvocation()
   * @model containment="true"
   * @generated
   */
  Expression getMethodInvocation();

  /**
   * Sets the value of the '{@link com.arsene.workflow.workflow.Assignment#getMethodInvocation <em>Method Invocation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method Invocation</em>' containment reference.
   * @see #getMethodInvocation()
   * @generated
   */
  void setMethodInvocation(Expression value);

} // Assignment
