/**
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.workflow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.arsene.workflow.workflow.WorkflowPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
