spring:
  application:
    name: authorization-server
#  sleuth:
#    enabled: true
#  zipkin:
#    enabled: true
#    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
  # ----------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        # dialect: "org.hibernate.dialect.MySQL8Dialect"
        format_sql: true
    generate-ddl: true
  # ----------------------------------------------------------
  datasource:
    url: "jdbc:mysql://localhost:3306/dbauth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    username: arsene
    password: arsene
    initialization-mode: always


# ----------------------------------------------------------
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: <signing-key>

# ----------------------------------------------------------

server:
  port: ${port:8000}
  forward-headers-strategy: framework
  servlet:
    context-path: /mms

# ----------------------------------------------------------

springdoc:
  swagger-ui:
    path: /api-docs/auth-server
# ----------------------------------------------------------

# For integration, this is treated as a client to Eureka server
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
# ----------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

