spring:
  application:
    name: storage-service
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}
# ----------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
# ----------------------------------------------------------
  datasource:
    url: "jdbc:mysql://dbauth:3306/dbauth?allowPublicKeyRetrieval=true&useSSL=false"
    username: arsene
    password: arsene
    initialization-mode: always

# ----------------------------------------------------------
security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: <signing-key>

# ----------------------------------------------------------

server:
  port: ${port:8000}

# ----------------------------------------------------------

springdoc:
  swagger-ui:
    path: /api-docs
# ----------------------------------------------------------

# For integration, this is treated as a client to Eureka server
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
# ----------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

