server:
  port: ${port:7000}
  forward-headers-strategy: framework
# Application details
spring:
  application:
    name: api-gateway-server

#  sleuth:
#    annotation:
#      enabled: true
#  zpkin:
#    enabled: true
#    base-url: ${ZIPKIN_SERVER:http://localhost:9411}

  #  Routing to appropriate microservices
  cloud:
    gateway:
      routes:
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true


# Management
management:
  endpoints:
    web:
      exposure:
        include: "*" # Enabling actuator
  endpoint:
    health:
      show-details: always
