server:
  port: ${port:7500}
  forward-headers-strategy: framework
# Application details
spring:
  application:
    name: api-gateway-server

  sleuth:
    annotation:
      enabled: true
  zpkin:
    enabled: true
    base-url: ${ZIPKIN_SERVER:http://localhost:9411}

  #  Routing to appropriate microservices
  cloud:
    gateway:
      routes:
        # Route for storage service
        - id: storage-service
          uri: lb://storage-service # the name of spring application
          predicates:
            - Path=/api/mms/store/**
          filters:
            - StripPrefix=1

            # Route for persistence api
        - id: persistence-api
          uri: http://localhost:3200 # the name of spring application
          predicates:
            - Path=/api/store/**
          filters:
            - StripPrefix=1

        # Route for model query service
        - id: model-query
          uri: lb://model-query
          predicates:
            - Path=/api/mms/query/**
          filters:
            - StripPrefix=1

        # Route for model transformation service
        - id: model-transformation
          uri: lb://model-transformation
          predicates:
            - Path=/api/mms/transform/**
          filters:
            - StripPrefix=1

        # Route for model validation service
        - id: model-validation
          uri: lb://model-validation
          predicates:
            - Path=/api/mms/validate/**
          filters:
            - StripPrefix=1

        # Route for model comparison
        - id: model-comparison
          uri: lb://model-comparison
          predicates:
            - Path=/api/mms/compare/**
          filters:
            - StripPrefix=1

        # Route for model merging
        - id: model-merging
          uri: lb://model-merging
          predicates:
            - Path=/api/mms/merge/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Management
management:
  endpoints:
    web:
      exposure:
        include: "*" # Enabling actuator
  endpoint:
    health:
      show-details: always
