spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/model_storage?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "arsene"
    password: "arsene"
    initialization-mode: always

  jpa:
    show-sql: true
    # spring.jpa.hibernate.ddl-auto is used for database initialization.
    # We set the value to update value so that a table will be created in the database
    # automatically corresponding to defined data model.
    # Any change to the model will also trigger an update to the table.
    # For production, this property should be validate.
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        format_sql: true
  application:
    name: storage-service
#  sleuth:
#    enabled: true
#  zipkin:
#    enabled: true
#    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

server:
  port: ${port:8089}

springdoc:
  swagger-ui:
    path: /api-docs

# For integration, this is treated as a client to Eureka server
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


