spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/model_storage?useSSL=false"
    username: "arsene"
    password: "arsene"

  jpa:
    show-sql: true
    # spring.jpa.hibernate.ddl-auto is used for database initialization.
    # We set the value to update value so that a table will be created in the database
    # automatically corresponding to defined data model.
    # Any change to the model will also trigger an update to the table.
    # For production, this property should be validate.
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
        format_sql: true
server:
  port: 8089

springdoc:
  swagger-ui:
    path: /api-docs