spring:
  application:
    name: model-transformation
# sleuth:
#   enabled: true
# zipkin:
#   enabled: true
#   base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

server:
  port: ${port:8085}
  forward-headers-strategy: framework
  servlet:
    context-path: /mms

springdoc:
  swagger-ui:
    path: /api-docs/transform

# For integration, this is treated as a client to Eureka server
eureka:
 client:
   service-url:
     defaultZone: ${EUREKA_SERVER:http://eureka-registry-server:8761/eureka}   #defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
 instance:
   prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always




