/**
 * generated by Xtext 2.25.0
 */
package com.arsene.workflow.web;

import com.arsene.workflow.WorkflowRuntimeModule;
import com.arsene.workflow.WorkflowStandaloneSetup;
import com.arsene.workflow.ide.WorkflowIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class WorkflowWebSetup extends WorkflowStandaloneSetup {
  @Override
  public Injector createInjector() {
    WorkflowRuntimeModule _workflowRuntimeModule = new WorkflowRuntimeModule();
    WorkflowIdeModule _workflowIdeModule = new WorkflowIdeModule();
    WorkflowWebModule _workflowWebModule = new WorkflowWebModule();
    return Guice.createInjector(Modules2.mixin(_workflowRuntimeModule, _workflowIdeModule, _workflowWebModule));
  }
}
